### ISSUE TITLE
Feature Request: Add --quiet flags for packagedescription 

### ISSUE THREAD

**Issue by idanblich** [jayree/sfdx-jayree-plugin#111]
Packagedescription commend is using ux.log to report the action and description done, see here [Line53](https://github.com/jayree/sfdx-jayree-plugin/blob/develop/src/commands/jayree/packagedescription/remove.ts#L53) 

This FR is to add --quiet to remove all logs , Suppress stdout output
--json should still provide this info

**Comment by jayree** [comment]
I will not implement this anymore
