### ISSUE TITLE
Trying to build full package.xml but got UNKNOWN_EXCEPTION

### ISSUE THREAD

**Issue by DarkSkull91** [jayree/sfdx-jayree-plugin#72]
Hi Jayree,

I run the following command in a sfdx project:
`sfdx jayree:packagexml`

and I got this message:
```
Generating package_jayree.xml... done
ERROR running jayree:packagexml:  UNKNOWN_EXCEPTION: invalid parameter value
```

Why?

**Comment by jayree** [comment]
@DarkSkull91 can you please provide the information from the USER_HOME_DIR/.sfdx/sfdx.log file. Thanks!
