### ISSUE TITLE
Add flag for jayree:automation:changeset to support outbound Change-set too

### ISSUE THREAD

**Issue by yaminm** [jayree/sfdx-jayree-plugin#92]
In order to provide quick deployments/validation without even wait that the change-set been pass to the target org I would like to have a flag/something else where I can choose if the change-set is in the inbound or outbound.
In addition, it will provide the ability to deploy/validate changes-set against unlink ENVs.

Thanks

**Comment by jayree** [comment]
I will not implement this anymore
